# Generated by Django 4.1.5 on 2023-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Age', models.CharField(max_length=3)),
                ('Gender', models.CharField(max_length=20)),
                ('PhNo', models.CharField(max_length=12)),
                ('District', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=10)),
                ('Account', models.CharField(max_length=50)),
                ('Materials', models.CharField(max_length=50)),
            ],
        ),
    ]
